image: Visual Studio 2017

build_script:
  - dotnet build hypepool.sln

test_script:
 - cd src\Tests\Hypepool.Core.Tests\ && dotnet xunit
 - cd src\Tests\Hypepool.Common.Tests\ && dotnet xunit
 - cd src\Tests\Hypepool.Monero.Tests\ && dotnet xunit 
